### ISSUE TITLE
Group calling

### ISSUE THREAD

**Issue by drunkplato** [datryn-ribdun/urbit-webrtc#12]
**Describe the feature you'd like**
- via invite code

### room

conceptually: `~lomder-librun/<room-code>`

- audio
- video
- cursors

### channel

 conceptually: `~lomder-librun/<room-code>/<channel-code>`

- /document - list of documents (filtered audio chat)
- /document/id-1 - channel where audio and cursor stream
- /document/id-2 - channel where audio and cursor stream

**Is your feature request related to a problem? Please describe.**

**Additional context**

**Comment by datryn-ribdun** [comment]
https://github.com/holium/campfire/issues/7
