### ISSUE TITLE
refactor state management to mobx

### ISSUE THREAD

**Issue by drunkplato** [datryn-ribdun/urbit-webrtc#13]
**Describe the feature you'd like**
- https://mobx-state-tree.js.org/intro/welcome
- Ballot state tree stuff: https://github.com/holium/ballot/blob/main/ui/src/logic/stores/booths/booth.ts

**Is your feature request related to a problem? Please describe.**

**Additional context**

**Comment by datryn-ribdun** [comment]
We chatted about this, and seems like sitching to just [mobx](https://mobx.js.org/) will do enough to help stage management. If it's ever not enough, it's pretty easy to go from mobx to mobx-state-tree

**Comment by drunkplato** [comment]
You can check out this as I have it refactored in the campfire fork: https://github.com/holium/campfire/tree/master/urchatfm/ui/src/stores

**Comment by drunkplato** [comment]
@drunkplato just checked this out. only feedback would be that `/campfire/ui/dist` in included in this push and should be ignored.
